# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html

import scrapy

class ScrapymoduleItem(scrapy.Item):
    # define the fields for your item here like:
    university = scrapy.Field()
    location = scrapy.Field()
    department = scrapy.Field()
    master = scrapy.Field()
    course = scrapy.Field()
    courseOverview = scrapy.Field()
    courseCode = scrapy.Field()
    startdate = scrapy.Field()
    duration = scrapy.Field()
    modules = scrapy.Field()
    assessment = scrapy.Field()
    career = scrapy.Field()
    opendate = scrapy.Field()
    deadline = scrapy.Field()
    applicationFee = scrapy.Field()
    tuitionFee = scrapy.Field()
    requirementsChinese = scrapy.Field()
    ielts = scrapy.Field()
    toefl = scrapy.Field()
    url = scrapy.Field()
    crawltime = scrapy.Field()
    alevel = scrapy.Field()
    ib = scrapy.Field()
    interview = scrapy.Field()
    portfolio = scrapy.Field()
    schoolTest = scrapy.Field()
    applicationDocuments = scrapy.Field()
    entryRequirements = scrapy.Field()
    howToApply = scrapy.Field()
    other = scrapy.Field()

# 2018/02/08 修改表tmp_shool_major
class SchoolItem(scrapy.Item):
    # define the fields for your item here like:
    university = scrapy.Field()
    country = scrapy.Field()
    city = scrapy.Field()
    website = scrapy.Field()
    department = scrapy.Field()
    programme = scrapy.Field()
    degree_level = scrapy.Field()
    degree_type = scrapy.Field()
    ucas_code = scrapy.Field()
    mode = scrapy.Field()
    application_date = scrapy.Field()
    deadline = scrapy.Field()
    start_date = scrapy.Field()
    degree_description = scrapy.Field()
    overview = scrapy.Field()
    duration = scrapy.Field()
    modules = scrapy.Field()
    application_fee = scrapy.Field()
    tuition_fee = scrapy.Field()
    teaching = scrapy.Field()
    assessment = scrapy.Field()
    career = scrapy.Field()
    location = scrapy.Field()
    entry_requirements = scrapy.Field()
    chinese_requirements = scrapy.Field()
    ATAS = scrapy.Field()
    GPA = scrapy.Field()
    average_score = scrapy.Field()
    accredited_university = scrapy.Field()
    Alevel = scrapy.Field()
    IB = scrapy.Field()
    IELTS = scrapy.Field()
    IELTS_L = scrapy.Field()
    IELTS_S = scrapy.Field()
    IELTS_R = scrapy.Field()
    IELTS_W = scrapy.Field()
    TOEFL = scrapy.Field()
    TOEFL_L = scrapy.Field()
    TOEFL_S = scrapy.Field()
    TOEFL_R = scrapy.Field()
    TOEFL_W = scrapy.Field()
    GRE = scrapy.Field()
    GMAT = scrapy.Field()
    LSAT = scrapy.Field()
    MCAT = scrapy.Field()
    working_experience = scrapy.Field()
    interview = scrapy.Field()
    portfolio = scrapy.Field()
    application_documents = scrapy.Field()
    how_to_apply = scrapy.Field()
    school_test = scrapy.Field()
    SATI = scrapy.Field()
    SATII = scrapy.Field()
    SAT_code = scrapy.Field()
    ACT = scrapy.Field()
    ACT_code = scrapy.Field()
    other = scrapy.Field()
    url = scrapy.Field()