from scrapy import cmdline
# cmdline.execute("scrapy crawl nclBen".split())
# cmdline.execute("scrapy crawl nclmasters".split())
# cmdline.execute("scrapy crawl qutben".split())
# cmdline.execute("scrapy crawl qutTaughtMasters".split())
# cmdline.execute("scrapy crawl qutResearchMasters".split())
# cmdline.execute("scrapy crawl curtinBen".split())
# cmdline.execute("scrapy crawl curtinTaughtMasters".split())
# cmdline.execute("scrapy crawl unisaBen".split())
# cmdline.execute("scrapy crawl deakinBen".split())
# cmdline.execute("scrapy crawl deakinTaughtMasters".split())
# cmdline.execute("scrapy crawl mqBen".split())
# cmdline.execute("scrapy crawl mqMasters".split())
# cmdline.execute("scrapy crawl rmitBen".split())
# cmdline.execute("scrapy crawl rmitTaughtMasters".split())
# cmdline.execute("scrapy crawl uwaBen".split())
# cmdline.execute("scrapy crawl scuBen".split())
# cmdline.execute("scrapy crawl scuMasters".split())
# cmdline.execute("scrapy crawl cquBen".split())
# cmdline.execute("scrapy crawl cquMasters".split())
# cmdline.execute("scrapy crawl csuBen".split())
# cmdline.execute("scrapy crawl csuMasters".split())
# cmdline.execute("scrapy crawl melbourneBen".split())
# cmdline.execute("scrapy crawl melbourneMasters".split())
# cmdline.execute("scrapy crawl melbourneMastersCopy".split())
# cmdline.execute("scrapy crawl vuBen".split())
# cmdline.execute("scrapy crawl vuMasters".split())
# cmdline.execute("scrapy crawl bondBen".split())
# cmdline.execute("scrapy crawl bondMasters".split())
# cmdline.execute("scrapy crawl utsBen".split())
# cmdline.execute("scrapy crawl utsMaster".split())
# cmdline.execute("scrapy crawl federationBen".split())
# cmdline.execute("scrapy crawl federationMasters".split())
# cmdline.execute("scrapy crawl uwaBen1".split())
# cmdline.execute("scrapy crawl uwaMasters".split())
# cmdline.execute("scrapy crawl adelaideBen".split())
# cmdline.execute("scrapy crawl adelaideResearch".split())
# cmdline.execute("scrapy crawl UNSWBen".split())
# cmdline.execute("scrapy crawl UNSWMaster".split())
# cmdline.execute("scrapy crawl UNSWResearch".split())

# 2018/3/27
cmdline.execute("scrapy crawl curtinResearch".split())

list1 = ["Bachelor of Aviation (Flying)",
"Bachelor of Aviation (Management)",
"Bachelor of Art Theory",
"Bachelor of Environmental Management",
"Bachelor of Art Theory / Bachelor of Arts",
"Bachelor of Actuarial Studies / Bachelor of Laws",
"Bachelor of Arts",
"Bachelor of Exercise Physiology",
"Bachelor of Actuarial Studies",
"Bachelor of Engineering (Honours) / Master of Biomedical Engineering ",
"Bachelor of Environmental Management / Bachelor of Arts",
"Bachelor of Art Theory / Bachelor of Social Research and Policy",
"Bachelor of Advanced Science (Hons) / Bachelor of Laws",
"Bachelor of Media (Communication and Journalism)",
"Bachelor of Medical Studies / Doctor of Medicine",
"Bachelor of Commerce",
"Bachelor of Material Science and Engineering (Honours) / Masters of Biomedical Engineering ",
"Bachelor of Life Sciences",
"Bachelor of Design (Honours)",
"Bachelor of Art Theory / Bachelor of Laws",
"Bachelor of Media (Public Relations and Advertising)",
"Bachelor of Medical Studies / Doctor of Medicine / Bachelor of Arts",
"Bachelor of Commerce (International)",
"Bachelor of Engineering (Honours) in Chemical Engineering ",
"Bachelor of Biotechnology (Hons)",
"Bachelor of Design (Honours) / Bachelor of Media in Public Relations and Advertising",
"Bachelor of Arts & Business / Bachelor of Laws",
"Bachelor of Media (Screen and Sound Production)",
"Bachelor of Economics",
"Bachelor of Engineering (Honours) in Industrial Chemistry",
"Bachelor of Medicinal Chemistry (Hons)",
"Bachelor of Fine Arts (Honours)",
"Bachelor of Arts / Bachelor of Laws",
"Bachelor of Music",
"Bachelor of Actuarial Studies",
"Bachelor of Food Science (Honours)",
"Bachelor of Nanoscience (Hons)",
"Bachelor of Fine Arts / Bachelor of Arts",
"Bachelor of City Planning (Hons) / Bachelor of Laws",
"Bachelor of Arts",
"Bachelor of Actuarial Studies",
"Bachelor of Engineering (Civil Engineering with Architecture)",
"Bachelor of Fine Arts / Bachelor of Education (Secondary)",
"Bachelor of Commerce / Bachelor of Laws",
"Bachelor of Arts / Bachelor of Education (Secondary)",
"Bachelor of Commerce",
"Bachelor of Engineering (Honours) in Civil Engineering ",
"Bachelor of Engineering (Hons) in Materials Science and Engineering",
"Bachelor of Media Arts (Honours)",
"Bachelor of Criminology & Criminal Justice / Bachelor of Laws",
"Bachelor of Commerce / Bachelor of Education (Secondary)",
"Bachelor of Commerce (International)",
"Bachelor of Engineering (Honours) in Civil Engineering ",
"Bachelor of Engineering (Hons) in Materials Science and Engineering / Bachelor of Commerce",
"Bachelor of Economics / Bachelor of Laws",
"Bachelor of Design (Honours) / Bachelor of Education (Secondary)",
"Bachelor of Economics",
"Bachelor of Engineering (Honours) in Environmental Engineering ",
"Bachelor of Materials Science and Engineering (Hons) / Engineering Science",
"Bachelor of Engineering (Hons) / Bachelor of Laws",
"Bachelor of Economics / Bachelor of Education (Secondary)",
"Bachelor of Actuarial Studies",
"Bachelor of Engineering (Honours) in Geospatial Engineering ",
"Bachelor of Science (Advanced Mathematics) (Hons)",
"Bachelor of Fine Arts / Bachelor of Laws",
"Bachelor of Fine Arts / Bachelor of Education (Secondary)",
"Bachelor of Commerce",
"Bachelor of Engineering (Honours) in Surveying ",
"Bachelor of Science (Advanced Mathematics) (Hons) / Bachelor of Arts",
"Bachelor of International Studies / Bachelor of Laws",
"Bachelor of Media Arts (Honours) / Bachelor of Education (Secondary)",
"Bachelor of Commerce (International)",
"Bachelor of Engineering (Honours) / Bachelor of Surveying",
"Bachelor of Science (Advanced Mathematics) / Bachelor of Engineering (Hons)",
"Bachelor of Media (Communication & Journalism) / Bachelor of Laws",
"Bachelor of Music / Bachelor of Education (Secondary)",
"Bachelor of Economics",
"Bachelor of Science (Advanced Mathematics) / Bachelor of Science (Computer Science) (Hons)",
"Bachelor of Media (Public Relations & Advertising) / Bachelor of Laws",
"Bachelor of Science / Bachelor of Education (Secondary)",
"Bachelor of Actuarial Studies",
"Bachelor of Engineering (Honours) in Computer Engineering ",
"Bachelor of Vision Science / Master of Clinical Optometry",
"Bachelor of Media (Screen & Sound Production) / Bachelor of Laws",
"Bachelor of Arts",
"Bachelor of Commerce",
"Bachelor of Engineering (Honours) in Software Engineering ",
"Bachelor of Advanced Science (Hons)",
"Bachelor of Medicinal Chemistry (Hons) / Bachelor of Laws",
"Bachelor of International Studies",
"Bachelor of Commerce (International)",
"Bachelor of Engineering (Honours) / Bachelor of Science (Computer Science)",
"Bachelor of Advanced Science (Hons) / Bachelor of Arts",
"Bachelor of Music / Bachelor of Laws",
"Bachelor of Arts",
"Bachelor of Economics",
"Bachelor of Engineering (Honours) in Bioinformatics Engineering",
"Bachelor of Advanced Science (Hons) / Bachelor of Engineering (Hons)",
"Bachelor of Psychological Science / Bachelor of Laws",
"Bachelor of Arts and Business",
"Bachelor of Actuarial Studies",
"Bachelor of Science (Computer Science)",
"Bachelor of Advanced Science (Hons) / Bachelor of Fine Arts",
"Bachelor of Psychology (Hons) / Bachelor of Laws",
"Bachelor of Criminology and Criminal Justice",
"Bachelor of Commerce",
"Bachelor of Science (Computer Science) / Bachelor of Media Arts (Hons) ",
"Bachelor of Advanced Science (Hons) / Bachelor of Science (Computer Science)",
"Bachelor of Science & Business / Bachelor of Laws",
"Bachelor of International Studies",
"Bachelor of Commerce (International)",
"Bachelor of Engineering (Honours) in Electrical Engineering ",
"Bachelor of Advanced Science (Hons)/Social Research and Policy",
"Bachelor of Science (Advanced Mathematics) / Bachelor of Laws",
"Bachelor of Social Research and Policy",
"Bachelor of Economics",
"Bachelor of Engineering (Honours) in Telecommunications Engineering ",
"Bachelor of Science",
"Bachelor of Science (Computer Science) / Bachelor of Laws",
"Bachelor of Social Work (Honours)",
"Bachelor of Actuarial Studies",
"Bachelor of Engineering / Master of Engineering in Electrical Engineering ",
"Bachelor of Science (Honours)",
"Bachelor of Science / Bachelor of Laws",
"Bachelor of Commerce",
"Bachelor of Advanced Mathematics (Hons) / Bachelor of Engineering (Honours)",
"Bachelor of Science (International)",
"Bachelor of Social Research & Policy / Bachelor of Laws",
"Bachelor of Commerce (International)",
"Bachelor of Advanced Mathematics (Hons) / Bachelor of Science (Computer Science)",
"Bachelor of Science / Bachelor of Arts",
"Bachelor of Social Work (Hons) / Bachelor of Laws",
"Bachelor of Economics",
"Bachelor of Advanced Science (Hons) / Bachelor of Engineering (Honours)",
"Bachelor of Science / Bachelor of Fine Arts",
"Bachelor of Information Systems",
"Bachelor of Advanced Science (Hons) / Bachelor of Science (Computer Science)",
"Bachelor of Science / Bachelor of Social Research and Policy",
"Bachelor of Actuarial Studies",
"Bachelor of Commerce/Bachelor of Science (Computer Science)",
"Bachelor of Science and Business",
"Bachelor of Commerce",
"Bachelor of Engineering (Honours) / Bachelor of Laws ",
"Bachelor of Psychological Science",
"Bachelor of Commerce (International)",
"Bachelor of Engineering (Honours) / Bachelor of Commerce",
"Bachelor of Psychological Science (Honours)",
"Bachelor of Economics",
"Bachelor of Engineering (Honours) / Bachelor of Science",
"Bachelor of Psychology (Hons)",
"Bachelor of Actuarial Studies",
"Bachelor of Engineering (Hons) / Bachelor of Arts ",
"Bachelor of Commerce",
"Bachelor of Music /Bachelor of Engineering (Honours)",
"Bachelor of Commerce (International)",
"Bachelor of Engineering (Honours) in Aerospace Engineering",
"Bachelor of Economics",
"Bachelor of Engineering (Honours) in Mechanical and Manufacturing Engineering",
"Bachelor of Actuarial Studies",
"Bachelor of Engineering (Honours) in Mechanical Engineering",
"Bachelor of Commerce",
"Bachelor of Engineering (Honours) in Mechatronic Engineering",
"Bachelor of Commerce (International)",
"Bachelor of Economics",
"Bachelor of Engineering (Honours) in Mining Engineering",
"Bachelor of Actuarial Studies",
"Bachelor of Commerce",
"Bachelor of Engineering (Honours) in Petroleum Engineering ",
"Bachelor of Commerce (International)",
"Bachelor of Engineering (Honours) in Photovoltaics and Solar Energy ",
"Bachelor of Economics",
"Bachelor of Engineering (Honours) in Renewable Energy Engineering ",
"Bachelor of Actuarial Studies",
"Bachelor of Commerce",
"Bachelor of Commerce (International)",
"Bachelor of Economics",]
listvalue = ["Whilst many trainee pilots aim at airline employment, you may also find careers in business aviation, training, charter flying and aerial survey work. * Flight training costs, which are in addition to tuition fees, are estimated in the range of A$122,000 - $144,000 for the duration of this program, depending on the advanced options chosen. Students who require more than 200 hours to achieve the required flying standards to Multi-Engine Instrument Rating may incur additional fees. ",
"Management within the industry often requires substantial knowledge of technical matters. Managers in aviation may also need specific knowledge of ",
"The creative and cultural industries are key drivers of growth in the contemporary global economy. Our graduates are sought after across a range of arts, cultural, entertainment, media and technology industries. Careers for Bachelor of Art Theory graduates include: Arts and Cultural Management, Policy Making and Administration, Creative Direction, Planning and Production, Art and Design Criticism, Communications and Journalism, Cultural and Creative Research and Scholarship, Multi-Platform Publishing and Distribution, Curatorship, Festival, Event and Museum Management, Design Thinking and Management, Public Programming and Engagement, Entrepreneurship, Strategist, Creative Social, Enterprise and Start-ups ",
"Environmental Consultant, Environmental Health Officer, Environmental Manager, Environmental Scientist, Conservation Scientist, Diver, Field Officer, Field Biologist, Park Ranger, Parks and Land Manager, Soil Scientist, Taxonomist, Policy Specialist, Marine Scientist ",
"Arts and cultural management, policy making and administration, Creative direction, planning and production, Art and design criticism, communications and journalism, Cultural and creative research and scholarship, Multi-platform publishing and distribution, Curatorship, festival, event and museum management, Design thinking and management, Public programming and engagement, Entrepreneurship, strategist, creative social enterprise and start-ups ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. Actuarial Studies/Law students are cross-trained to become uniquely skilled in both areas, with the ability to provide comprehensive strategic, commercial, and legal advice to the financial and insurance services industry, regulatory bodies, government organisations, consultancy firms, and international organisations. ",
"As a Bachelor of Arts graduate you will develop transferable skills suited to a wide range of careers. These skills include critical and creative problem solving, persuasive communication and presentation skills, research skills, an understanding of human behaviour, and respect for social, cultural and individual diversity. Our graduates can be found in the following careers: Diplomacy, publishing, the arts and creative industries, international affairs, education, journalism, social justice, politics, university and public administration, interpreting and translating, business and entrepreneurship, media and research. ",
"Exercise physiologists are employed in rehabilitation clinics and hospitals working in post-acute rehabilitation, aged care, sports medicine clinics, corporate health and private practice for rehabilitation/exercise prescription for people requiring specialist guidance (for example workplace rehabilitation departments). The degree also provides excellent preparation to apply for graduate degrees in nutrition, physiotherapy and other allied-health professions, or research higher degrees (Masters or PhD). ",
"There is strong demand for graduates in actuarial studies, especially in the financial services, insurance and superannuation industry. As a graduate, you can work as an actuarial analyst, consultant, asset management trainee, credit analyst, forecasting analyst, insurance analyst, risk assessment officer, statistical research analyst, superannuation advisor or wealth management analyst. ",
"This dual degree program is specifically designed for undergraduate students wishing to pursue a career in either Engineering or Biomedical Engineering. Biomedical Engineering is the application of engineering principles to developing technologies and solving problems in a diverse range of health care related fields e.g. implantable bionics, drug delivery systems, medical imaging, radiotherapies, orthopaedic devices, telemedicine, robotic surgery, cell and tissue engineering, records management, physical rehabilitation and others. This program is integrated to provide fundamental engineering skills with an undergraduate focus on Materials Science and Engineering and specialist postgraduate level training in Biomedical Engineering. ",
"Science Communicator, Botanist, Environmental Health Officer, Environmental Consultant, Policy Specialist, Environmental Manager ",
"Arts and cultural management, policy making and administration, Creative direction, planning and production, Art and design criticism, communications and journalism, Cultural and creative research and scholarship, Multi-platform publishing and distribution, Curatorship, festival, event and museum management, Design thinking and management, Public programming and engagement, Entrepreneurship, strategist, creative social enterprise and start-ups ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. This degree prepares graduates for legal practice as a solicitor or barrister, in-house legal counsel, or to work in research, technology, science, mathematics, education, public policy. There are additional opportunities to become a patent attorney. ",
"The Bachelor of Media (Communication and Journalism) prepares you for a career in journalism and professional communications across a range of contemporary platforms. Graduates have the skills to pursue a career in corporate organisational and public sector communication. Career options include: Journalism (online, print, broadcast), corporate communications, media account management, internal communications, corporate affairs, media relations and social media. ",
"Medicine prepares students for entry into the medical professions. ",
"As a graduate, you will be equipped with specialist technical skills which are the building blocks for a career in business, as well as developed analytical skills. You will be qualified to pursue a range of careers across local and international organisations, government and not-for-profit organisations and work as an accountant, economist, strategy consultant, business manager, marketing specialist, information systems consultant, taxation advisor, investment banker, or policy advisor. ",
"",
"Anatomist, Biochemist, Botanist, Life Scientist, Marine Scientist, Environmental Scientist, Chemist, Environmental Health Officer, Food Scientist/Technologist, Geologist, Laboratory Technician, Field Biologist, Wildlife Biologist, Diver, Anthropologist, Oceanographer, Toxicologist, Cartographer, Conservation Scientist, Park Ranger, Parks and Land Manager, Pharmacologist, Human Resources Manager, Community Development Worker, Marketing Professional, Quality Assurance Specialist, Taxonomist, Formulation Chemist, Regulations Manager, Field Officer, Microbiologist, Environmental Consultant, Forensic Scientist, Geneticist, Laboratory Manager ",
"UNSW's Bachelor of Design (Hons) prepares students to be dynamic design professionals and studio practitioners. Our graduates are highly sought after across a broad range of professional design disciplines in media and technology industries, global institutions, major corporations, creative and bespoke agencies. Graduates find employment in areas including: Graphics, media and digital design, Interaction design, Communications, branding and advertising, Design management and strategy, Social innovation and entrepreneurship, App development, data visualisation and responsive design, Creative consultancies, design and media, studios, design-led businesses, Environmental, spatial, interior and architectural design practices, Object, furniture and lighting design, Film, television, online and mobile production and post-production, Design for exhibitions, galleries and museums, Costume, theatre and events design, Design teaching and academia, Jewellery design, Packaging, illustration and publishing, Textile, fabric, wearable design and fashion ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. Art Theory/Law graduates are likely to be employed in the arts or law fields, but broader opportunities exist for careers in arts management and policy. The complementary nature of this dual degree will be highly regarded by employers in the industry. ",
"Bachelor of Media (Public Relations and Advertising) graduates have advanced skills and knowledge in professional work relevant to public relations, media relations and organisational communication. Career options include: Public relations, advertising and account management, advertising creative services, corporate affairs, media relations, social media, and communications. ",
"",
"As a graduate, you can find employment in diverse professions within the commerce industry depending on your choice of major in the commerce degree. You can work in government agencies including foreign affairs, investment banks and other financial institutions with international links as well as nongovernment organisations. ",
"Chemical engineers design and operate large-scale chemical process equipment and factories safely, efficiently and in an environmentally responsible manner. They produce a diverse range of materials from fuels and circuit boards to processed foods, life saving pharmaceuticals and filtered clean water. They also develop alternative energy sources – alcohol and biofuels from crops and efficient ways to utilise solar energy. ",
"As a graduate, you can expect to find employment in a wide range of organisations including start-up companies developed to commercialise new research findings, established companies applying new biological techniques, medical and biological research organisations and a range of commercially related activities such as patents and venture capital. ",
"Graphics, media and digital design, Communications, communications strategy, advertising, branding and advertising, Design management and strategy, digital media strategy, experiential design, experiential marketing, marketing, Social innovation and entrepreneurship, App development, data visualisation and responsive design, Creative consultancies, design and media studios, design-led businesses. ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. Graduates can find themselves in an extensive range of careers in business, finance, government/international relations, social research, or more traditional legal practice. ",
"The Bachelor of Media in Screen and Sound Production develops practical, creative and conceptual skills in screen and sound-based media with a sophisticated understanding of the theoretical and industry environments of contemporary film and media. Your knowledge and professional skills will prepare you for careers in a wide range of media and communication, audio-visual, music, film and media industries. ",
"This degree opens up a rewarding career in many areas of business, finance or government. Graduate positions may include: Business analyst, Economic forecaster, Graduate economist, Management consultant, Policy advisor, Statistical analyst, Superannuation advisor. Related careers in accounting, finance, human resource management, information systems, marketing and taxation. ",
"As a graduate, you can work in the chemical and process industries as a research scientist, development chemist, technical representative or as a plant/company manager. Graduates may find employment with pharmaceutical, cosmetic or food industries; mineral processing plants; polymer, new materials, paper, fertiliser and wine making industries or major companies involved in pollution control. ",
"Medicinal chemistry graduates are in demand for employment in the pharmaceutical and biotechnology industries. As a graduate, you will be equipped with skills in modern molecular biology and pharmacology. These skills are underpinned with a comprehensive background in chemistry with relevant synthetic skills necessary for synthesising complex drug candidates. You can also find employment opportunities within the research, government, management, legal and education sectors. ",
"UNSW Art and Designs BFA equips students with transferable skills and insights, so that graduates find employment across the creative and cultural industries including: Advertising, Art Direction and Communication, Arts And Cultural Administration and Policy Making, Arts Education and Training Commercial and News Photography, Curating and Program Management in Festivals, Museums, Galleries and Public Spaces, Arts Writing, Publishing and Criticism, Exhibition Planning, Design and Installation, Entertainment, Media and Technology Industries, Theatre, Film and Television Production, Urban Planning, Site Activation and Public Art, Practising artist in your field of expertise ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. This program provides excellent preparation for a career in any number of fields including business, finance, government/international relations and the more traditional areas of legal practice, in both law firms and corporations. ",
"Our graduates are highly skilled musicians with specialist knowledge and practical skills in music cognition, analysis and performance. Career options include: Performance, teaching, broadcasting, arts administration, arts management, composition, conducting, arts advocacy, music recording and film industries, research, and arts journalism. ",
"There is strong demand for graduates in actuarial studies, especially in the financial services, insurance and superannuation industry. As a graduate, you can work as an actuarial analyst, consultant, asset management trainee, credit analyst, forecasting analyst, insurance analyst, risk assessment officer, statistical research analyst, superannuation advisor or wealth management analyst. ",
"Food technologist, new product developer, food testing, laboratory scientist, food microbiologist, quality manager, nutritionist. ",
"Graduates pursue careers across a wide range of disciplines. Many pursue careers in research while others work in the science and technology sector or research and development. Start-up companies and other organisations seek to exploit nanotechnology principles in the manufacture of devices and products. They employ nanotechnology graduates because of their broad training, capacity to think critically and laterally, and their problem-solving abilities ",
"Arts and cultural administration and policy making, Arts education and training, Arts writing, publishing and criticism, Commercial and news photography, Curating and program management in festivals, museums, galleries and public spaces, Exhibition planning, design and installation, Entertainment, media and technology industries, Theatre, film and television production, Urban planning, site activation and public art ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. The program allows you to obtain two professionally accredited degrees and provides excellent preparation for careers in law firms with specialist local government/planning law practices, related government departments and regulatory bodies, local councils and town planning consultancies. ",
"As a Bachelor of Arts graduate you will develop transferable skills suited to a wide range of careers. These skills include critical and creative problem solving, persuasive communication and presentation skills, research skills, an understanding of human behaviour, and respect for social, cultural and individual diversity. Our graduates can be found in the following careers: Diplomacy, publishing, the arts and creative industries, international affairs, education, journalism, social justice, politics, university and public administration, interpreting and translating, business and entrepreneurship, media and research. ",
"There is strong demand for graduates in actuarial studies, especially in the financial services, insurance and superannuation industry. As a graduate, you can work as an actuarial analyst, consultant, asset management trainee, credit analyst, forecasting analyst, insurance analyst, risk assessment officer, statistical research analyst, superannuation advisor or wealth management analyst. ",
"Specialist structural engineering, consultants, construction, and contracting companies, federal, state and local government organisations, airport and harbour authorities, project developers, financial and management consultants in large corporations. ",
"Arts and cultural administration and policy making, Arts education and training, Arts writing, publishing and criticism, Commercial and news photography, Curating and program management in festivals, museums, galleries and public spaces, Exhibition planning, design and installation, Entertainment, media and technology industries, Theatre, film and television production, Urban planning, site activation and public art ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. Graduates are found in an extensive range of careers including major law firms and accountancy practices, investment and trading banks, corporations, regulatory and advisory bodies, government instrumentalities, consultancy firms and international organisations. ",
"As a graduate, you can work in secondary school teaching in Australia and internationally, as well as in education, corporate training and management. ",
"As a graduate, you will be equipped with specialist technical skills which are the building blocks for a career in business, as well as developed analytical skills. You will be qualified to pursue a range of careers across local and international organisations, government and not-for-profit organisations and work as an accountant, economist, strategy consultant, business manager, marketing specialist, information systems consultant, taxation advisor, investment banker, or policy advisor. ",
"Many civil engineers work in an office environment where they investigate, plan, design and manage projects; others manage and supervise construction projects on site. Employment can be found with specialist consulting firms, construction and contracting companies, large public companies, federal, state and local government organisations, airport and harbour authorities, project developers, financial and management consultants, and many more. ",
"As a materials science and engineering graduate, you can find employment with primary production industries, research and development in industrial laboratories or research institutions, consultants, the materials producing industries, utilities (such as power generators, railways and airlines) or the manufacturing sector. ",
"The Bachelor of Media Arts (Honours) produces creative content developers with sound technical and problem solving skills and the ability to work creatively and collaboratively across a diverse and wide range of disciplines in the creative media world. As a graduate, you will be a lead player in the cultural, digital, entertainment, creative media and technology industries with strengths in creative design and technical innovation. Our Graduates find employment in areas including: Animation Design and Production, Digital Publishing and Communications, Video, Online and Mobile Media, Interaction, User-Experience and Environments, Game Development and Production, Digital Strategy, Film, Television, Online and Mobile Production, Multiplatform Media Development and Production, Production Management and Development, Sound Design, Composition and Production, Scientific Imaging and Visualization, Media Strategy and Planning, Entrepreneurship, Innovation and Digital Media Start-ups ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. Career opportunities exist with criminal justice agencies such as the Attorney-General's Department, Police, Prisons, Customs, ASIO, Magistrates, District and Supreme Courts, Australian Bureau of Statistics, and practising as a criminal barrister. ",
"As a graduate, you can work in secondary school teaching in Australia and internationally, as well as careers in education, corporate training and management. ",
"As a graduate, you can find employment in diverse professions within the commerce industry depending on your choice of major in the commerce degree. You can work in government agencies including foreign affairs, investment banks and other financial institutions with international links as well as nongovernment organisations. ",
"Many civil engineers work in an office environment where they investigate, plan, design and manage projects; others manage and supervise construction projects on site. Employment can be found with specialist consulting firms, construction and contracting companies, large public companies, federal, state and local government organisations, airport and harbour authorities, project developers, financial and management consultants, and many more. ",
"Market Researcher / Analyst, Materials Scientist, Patent Specialist, Product Analyst, Product Developer, Quality Assurance Specialist, Regulations Manager, Business Consultant, Finance Manager, Risk Analyst, Laboratory Manager, Venture Capitalist, Metallurgist, Policy Specialist, Entrepreneur, Bank Manager, Inventor ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. Graduates are likely to be employed in many areas of law, government and business including finance companies, stockbroking firms, banks, regulatory bodies, government departments, consultancy and research firms and international organisations. ",
"As a graduate, you can work in secondary school teaching in Australia and internationally, as well as careers in education, corporate training and design. ",
"This degree opens up a rewarding career in many areas of business, finance or government. Graduate positions may include: Business analyst, Economic forecaster, Graduate economist, Management consultant, Policy advisor, Statistical analyst, Superannuation advisor. Related careers in accounting, finance, human resource management, information systems, marketing and taxation. ",
"Some environmental engineers work in an office environment where they investigate, plan, design and manage projects. Others are involved in field studies working on site. Most manage to combine both office and field work in an exciting, challenging and rewarding career. ",
"Analytical Chemist, Formulation Chemist, Industrial Chemist, Materials Scientist, Metallurgist, Product Analyst, Product Developer, Quality Assurance Specialist, Regulations Manager, Forensic Scientist, Risk Analyst, Inventor ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. Employment opportunities exist with a range of medium to large and specialist legal firms and with national and multinational engineering and construction corporations. ",
"As a graduate, you can work in secondary school teaching in Australia and internationally, as well as a variety of careers in education, corporate training and management. ",
"There is strong demand for graduates in actuarial studies, especially in the financial services, insurance and superannuation industry. As a graduate, you can work as an actuarial analyst, consultant, asset management trainee, credit analyst, forecasting analyst, insurance analyst, risk assessment officer, statistical research analyst, superannuation advisor or wealth management analyst. ",
"You could work in land development and planning, cadastral surveying, hydrographic surveying, engineering and mining surveying, precise measurement and positioning, cartography, environmental monitoring and in a variety of geospatial IT industries. ",
"Mathematician, Statistician, Finance Manager, Computer Scientist, Computer Programmer, Auditor, Astronomer, Meteorologist, Epidemiologist, Bank Manager, Business Consultant, Climate Scientist, Data Scientist, Database Administrator, Climate Analyst, Environmental Consultant, Hedge Fund Manager, Risk Analyst, Management Consultant, Market Researcher / Analyst, Financial Trader, Venture Capitalist, Policy Specialist, Transportation Analyst, Entrepreneur ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. As a Fine Arts/Law graduate, you're likely to be employed in law, at a law firm, gallery, museum or arts foundation, or as an independent artist, but opportunities also exist in the broader creative arena. ",
"As a graduate, you can work in secondary school teaching in Australia and internationally, as well as careers in education, corporate training and the arts. ",
"As a graduate, you will be equipped with specialist technical skills which are the building blocks for a career in business, as well as developed analytical skills. You will be qualified to pursue a range of careers across local and international organisations, government and not-for-profit organisations and work as an accountant, economist, strategy consultant, business manager, marketing specialist, information systems consultant, taxation advisor, investment banker, or policy advisor. ",
"You could work in land development and planning, cadastral surveying, hydrographic surveying, engineering and mining surveying, precise measurement and positioning, cartography, environmental monitoring and in a variety of geospatial IT industries. ",
"Auditor, Finance Manager, Oceanographer, Quantitative Analyst, Statistician, Bank Manager, Business Consultant, Environmental Consultant, Management Consultant, Market Researcher / Analyst ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. A global marketplace demands graduates with both skills and an international perspective. As a graduate, you can be employed by large corporations involved in international trade, government departments, foreign affairs and international organisations like the United Nations. ",
"As a graduate, you can work in secondary school teaching in Australia and internationally, as well as careers in education, corporate training and the media arts industry. ",
"As a graduate, you can find employment in diverse professions within the commerce industry depending on your choice of major in the commerce degree. You can work in government agencies including foreign affairs, investment banks and other financial institutions with international links as well as nongovernment organisations. ",
"",
"Auditor, Mathematician, Computer Scientist, Computer Programmer, Quantitative Analyst, Statistician, Business Systems Analyst, Biomedical Engineer, Climate Scientist, Data Scientist, Database Administrator, Patent Specialist, Venture Capitalist, Meteorologist, Transportation Analyst, Epidemiologist ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. This degree combination can also open up career pathways for graduates interested in becoming lawyers within the media industry, or finding themselves working for large national and international law firms, public relations, advertising and media companies, arts management or in entertainment law. ",
"As a graduate, you can work in the areas of secondary teaching, music administration, music production, broadcasting and recording, performance planning, composing and arranging. ",
"This degree opens up a rewarding career in many areas of business, finance or government. Graduate positions may include: Business analyst, Economic forecaster, Graduate economist, Management consultant, Policy advisor, Statistical analyst, Superannuation advisor. Related careers in accounting, finance, human resource management, information systems, marketing and taxation. ",
"Mathematician, Business Systems Analyst, Computer Scientist, Computer Programmer, Data Scientist, Database Administrator, Market Researcher / Analyst, Quantitative Analyst, Risk Analyst, Statistician, Venture Capitalist, Transportation Analyst, Entrepreneur, Epidemiologist ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. Opportunities exist in a wide range of careers in specialist entertainment law practices with both large and boutique firms, and also in public relations and arts management with communication, advertising and media companies and public sector organisations. ",
"The Education program prepares graduates for professions in secondary school teaching in Australia and internationally, as well as a variety of careers in education, corporate training and science. ",
"There is strong demand for graduates in actuarial studies, especially in the financial services, insurance and superannuation industry. As a graduate, you can work as an actuarial analyst, consultant, asset management trainee, credit analyst, forecasting analyst, insurance analyst, risk assessment officer, statistical research analyst, superannuation advisor or wealth management analyst. ",
"Computer engineering graduates are ideally suited to jobs involving the development of hardware software systems for communications, electronics or process control, and work in such diverse industries as telecommunications, power, defence, or gaming machines. ",
"Optometrist, Vision Scientist ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. This degree combination is relevant to students interested in becoming lawyers within the media landscape or in audio-visual production industries. Graduates can find themselves in a wide range of careers, including working for large national and international law firms, or corporations in the entertainment / audio-visual production space. ",
"As a Bachelor of Arts graduate you will develop transferable skills suited to a wide range of careers. These skills include critical and creative problem solving, persuasive communication and presentation skills, research skills, an understanding of human behaviour, and respect for social, cultural and individual diversity. Our graduates can be found in the following careers: Diplomacy, publishing, the arts and creative industries, international affairs, education, journalism, social justice, politics, university and public administration, interpreting and translating, business and entrepreneurship, media and research. ",
"As a graduate, you will be equipped with specialist technical skills which are the building blocks for a career in business, as well as developed analytical skills. You will be qualified to pursue a range of careers across local and international organisations, government and not-for-profit organisations and work as an accountant, economist, strategy consultant, business manager, marketing specialist, information systems consultant, taxation advisor, investment banker, or policy advisor. ",
"Graduates have strengths in design techniques and experience in software design and development, which equips them for a wide range of careers. Employment may involve the business sector, which utilises their knowledge and abilities in designing advanced information systems; building technical systems for the medical, power and transport industries; the burgeoning telecommunications area, exploiting, or even developing new network technologies. ",
"Anatomist, Analytical Chemist, Botanist, Cartographer, Chemist, Climate Analyst, Climate Scientist, Conservation Scientist, Environmental Consultant, Environmental Scientist, Food Scientist/Technologist, Field Biologist, Field Officer, Formulation Chemist, Geologist, Geographer, Industrial Chemist, Inventor, Laboratory Technician, Life Scientist, Market Researcher / Analyst, Materials Scientist, Medical Scientist, Meteorologist, Microbiologist, Oceanographer, Parks and Land Manager, Patent Specialist, Pharmacologist, Physicist, Product Analyst, Product Developer, Quality Assurance Specialist, Regulations Manager, Science Communicator, Soil Scientist, Taxonomist, Toxicologist, Wildlife Biologist, Zoologist, Vision Scientist, Epidemiologist, Biochemist, Biotechnologist, Forensic Scientist, Geneticist, Risk Analyst, Community Development Worker, Laboratory Manager, Management Consultant, Medical Technician, Policy Specialist, Marine Scientist, Anthropologist ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. Graduating with qualifications in both Medicinal Chemistry and Law opens up a range of possible career opportunities in both the legal and scientific fields. Graduates may find themselves working in legal roles with national and international law firms, corporations and government bodies, or working as a medicinal chemist, patent specialist, product analyst, product developer, quality assurance specialist, regulations manager, forensic scientist, formulation chemist, immunologist, laboratory manager, medical scientist or venture capitalist. ",
"International Studies graduates are prepared for careers in the global market. They are found working worldwide in areas including: business, government agencies (Such as the Department of Foreign Affairs and Trade), investment banks, and other financial institutions, non-government organisations, the United Nations, journalism and media, tourism and trade, and diplomacy. ",
"As a graduate, you can find employment in diverse professions within the commerce industry depending on your choice of major in the commerce degree. You can work in government agencies including foreign affairs, investment banks and other financial institutions with international links as well as nongovernment organisations. ",
"",
"Anthropologist, Community Development Worker, Environmental Manager, Environmental Health Officer, Field Officer, Human Resources Manager, Management Consultant, Marketing Professional, Parks and Land Manager, Science Communicator, Environmental Consultant, Laboratory Manager, Market Researcher / Analyst ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. Music/Law graduates can often find themselves in a wide range of careers, including working for large national and international law firms, music and entertainment law or audio-visual production industries. ",
"As a Bachelor of Arts graduate you will develop transferable skills suited to a wide range of careers. These skills include critical and creative problem solving, persuasive communication and presentation skills, research skills, an understanding of human behaviour, and respect for social, cultural and individual diversity. Our graduates can be found in the following careers: Diplomacy, publishing, the arts and creative industries, international affairs, education, journalism, social justice, politics, university and public administration, interpreting and translating, business and entrepreneurship, media and research. ",
"This degree opens up a rewarding career in many areas of business, finance or government. Graduate positions may include: Business analyst, Economic forecaster, Graduate economist, Management consultant, Policy advisor, Statistical analyst, Superannuation advisor. Related careers in accounting, finance, human resource management, information systems, marketing and taxation. ",
"As a graduate, you can work with biotechnology and pharmaceutical companies, companies in the information and communications technology sector, public sector organisations, public and private research organisations. ",
"Hydrologist, Business Systems Analyst, Climate Scientist, Computer Scientist, Database Administrator, Food Scientist/Technologist, Forensic Scientist, Formulation Chemist, Laboratory Technician, Medical Scientist, Medical Technician, Venture Capitalist, Meteorologist, Transportation Analyst, Environmental Scientist, Epidemiologist ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. This dual degree combination provides excellent preparation for careers in criminology, dispute resolution and negotiation, where an understanding of both law and psychology are beneficial. ",
"This degree provides you with the skills to work in management, marketing and strategy roles in a range of industries and organisations. Your choice of major and minor will help shape your career options. You will develop skills, capabilities and ways of thinking critically, which are highly valued by employers and professions including critical and creative problem solving, persuasive communication and presentation skills, research skills, an understanding of human behaviour, and respect for social, cultural and individual diversity. ",
"There is strong demand for graduates in actuarial studies, especially in the financial services, insurance and superannuation industry. As a graduate, you can work as an actuarial analyst, consultant, asset management trainee, credit analyst, forecasting analyst, insurance analyst, risk assessment officer, statistical research analyst, superannuation advisor or wealth management analyst. ",
"Graduates are employed in a wide range of industries, in government departments and private firms (including software development companies like Microsoft, IBM and Sun Microsystems). They commonly work as programmers and analysts, but some find that working with people in user support, or as a network administrator, is more to their liking. ",
"Anatomist, Anthropologist, Botanist, Chemist, Diver, Field Officer, Geologist, Geographer, Microbiologist, Oceanographer, Quality Assurance Specialist, Regulations Manager, Science Communicator, Soil Scientist, Taxonomist, Toxicologist, Zoologist ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. This dual degree combination provides excellent preparation for careers in criminology, dispute resolution and negotiation, where an understanding of both law and psychology are beneficial. ",
"Our graduates can be found working as policy analysts and advisors, research officers, project managers and research designers in private, government and non-government sectors. ",
"As a graduate, you will be equipped with specialist technical skills which are the building blocks for a career in business, as well as developed analytical skills. You will be qualified to pursue a range of careers across local and international organisations, government and not-for-profit organisations and work as an accountant, economist, strategy consultant, business manager, marketing specialist, information systems consultant, taxation advisor, investment banker, or policy advisor. ",
"",
"Business Systems Analyst, Computer Scientist, Computer Programmer, Inventor, Oceanographer, Quantitative Analyst, Market Researcher / Analyst, Statistician, Database Administrator, Management Consultant, Transportation Analyst, Entrepreneur, Epidemiologist ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. This is the perfect dual degree for the lawyers and entrepreneurs of the future - people who love science and understand the worlds of law and business. This degree prepares graduates for employment in a wide range of legal and business careers, while opportunities also exist to become a patent attorney, contribute to policy formulation at the national level or become an in-house counsel. ",
"International Studies graduates are prepared for careers in the global market. They are found working worldwide in areas including: business, government agencies (Such as the Department of Foreign Affairs and Trade), investment banks, and other financial institutions, non-government organisations, the United Nations, journalism and media, tourism and trade, and diplomacy. ",
"As a graduate, you can find employment in diverse professions within the commerce industry depending on your choice of major in the commerce degree. You can work in government agencies including foreign affairs, investment banks and other financial institutions with international links as well as nongovernment organisations. ",
"Potential employers include service industries such as Telstra, Optus and electricity authorities; large private industrial groups, such as Ericsson, Alstom, BHP, Boeing Australia, Honeywell, Motorola, IBM and Alcatel; small innovative private firms specialising in the application of new technologies to new products and services, in a range of areas such as telecommunications and wireless electronics, internet services and biomedical instrumentation. ",
"Science Communicator, Anthropologist, Community Development Worker, Climate Analyst, Policy Specialist, Entrepreneur, Environmental Consultant ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. This dual degree will allow you to develop the professional skills and practical experience that will make you a sought-after employee in both the science and legal industries. Graduates are employed in a wide range of legal, financial services and consulting careers, and additional opportunities exist to become a patent attorney, contribute to policy formulation at the national level or become an in-house counsel. ",
"As a graduate you will design research, evaluate policy, manage projects, conduct interviews, field high quality social surveys, use statistics and understand their role in social change. Our Social Research and Policy graduates are highly successful in gaining employment in diverse roles and areas such as: Public sector - Research manager, policy analyst, political adviser, project manager. Community sector - Program management, community development, information management, advocacy and innovation. Private sector - Organisational management. marketing, market research, corporate affairs management, private consultant, research consultant. ",
"This degree opens up a rewarding career in many areas of business, finance or government. Graduate positions may include: Business analyst, Economic forecaster, Graduate economist, Management consultant, Policy advisor, Statistical analyst, Superannuation advisor. Related careers in accounting, finance, human resource management, information systems, marketing and taxation. ",
"The demand for graduates of telecommunications is rapidly increasing as the technology advances and broadens its scope. Potential employers include major telecommunications service providers; large private industrial groups such as JDS, Uniphase and Alcatel; smaller service and technology providers, all highly specialised and technologically sophisticated. ",
"Chemist, Biochemist, Industrial Chemist, Marine Scientist, Environmental Scientist, Food Scientist/Technologist, Life Scientist, Materials Scientist, Medical Scientist, Soil Scientist, Laboratory Technician, Medical Technician, Zoologist, Botanist, Anatomist, Astronomer, Environmental Health Officer, Environmental Manager, Finance Manager, Geologist, Physicist, Field Biologist, Wildlife Biologist, Geographer, Anthropologist, Product Analyst, Oceanographer, Toxicologist, Meteorologist, Cartographer, Conservation Scientist, Park Ranger, Parks and Land Manager, Pharmacologist, Patent Specialist, Science Communicator, Human Resources Manager, Market Researcher / Analyst, Community Development Worker, Marketing Professional, Statistician, Quality Assurance Specialist, Taxonomist, Product Developer, Formulation Chemist, Regulations Manager, Field Officer, Microbiologist, Environmental Consultant, Vision Scientist, Biotechnologist, Climate Scientist, Forensic Scientist, Geneticist, Laboratory Manager ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. Graduates can be found in a wide range of careers both in legal and specialist technology based roles in private practice, corporations, banks, government, accounting and consultancy firms. Areas of expertise may include intellectual property, computer forensics, information technologies or cyberspace laws both in Australia and internationally. ",
"Opportunities for social workers are diverse and include work in government services, hospitals, local government and social planning and in the organisation and delivery of services for local residents, non-government welfare agencies, and industrial/corporate settings. Social workers can also work in private practice as counsellors or psychotherapists or as consultants in planning and social policy, international aid, politics, rights and education. ",
"There is strong demand for graduates in actuarial studies, especially in the financial services, insurance and superannuation industry. As a graduate, you can work as an actuarial analyst, consultant, asset management trainee, credit analyst, forecasting analyst, insurance analyst, risk assessment officer, statistical research analyst, superannuation advisor or wealth management analyst. ",
"",
"Anatomist, Biotechnologist, Chemist, Climate Analyst, Diver, Field Officer, Food Scientist/Technologist, Geographer, Laboratory Technician, Materials Scientist, Mathematician, Medical Technician, Medical Scientist, Oceanographer, Patent Specialist, Product Analyst, Product Developer, Quality Assurance Specialist, Regulations Manager, Science Communicator, Vision Scientist, Research Officer ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. Employment opportunities exist in legal practice as a solicitor or barrister, in-house counsel, work in research, technology, science, mathematics, education, public policy and opportunities to become a patent attorney. ",
"As a graduate, you will be equipped with specialist technical skills which are the building blocks for a career in business, as well as developed analytical skills. You will be qualified to pursue a range of careers across local and international organisations, government and not-for-profit organisations and work as an accountant, economist, strategy consultant, business manager, marketing specialist, information systems consultant, taxation advisor, investment banker, or policy advisor. ",
"",
"Environmental Scientist, Life Scientist, Physicist, Zoologist, Oceanographer, Toxicologist, Cartographer, Conservation Scientist, Park Ranger, Parks and Land Manager, Pharmacologist, Human Resources ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. Graduates are employed in a range of legal and social justice related industries. There are also opportunities for careers in the public sector, community service, international aid agencies and business. ",
"As a graduate, you can find employment in diverse professions within the commerce industry depending on your choice of major in the commerce degree. You can work in government agencies including foreign affairs, investment banks and other financial institutions with international links as well as nongovernment organisations. ",
"",
"Anatomist, Anthropologist, Chemist, Community Development Worker, Conservation Scientist, Diver, Environmental Consultant, Environmental Manager, Field Biologist, Field Officer, Geographer, Geologist, Human Resources Manager, Laboratory Manager, Life Scientist, Market Researcher / Analyst, Marketing Professional, Microbiologist, Patent Specialist, Product Analyst, Science Communicator, Taxonomist, Venture Capitalist ",
"Your Law dual degree will open up a wide range of career opportunities in myriad fields. The skills you will gain at UNSW Law are highly transferrable. Employers seek out our graduates for their critical thinking and analytical skills. When it comes to your career, there will be any number of options available to you. Graduates are AASW and ASWEAS accredited and can be employed in areas including consumer protection, tenancy obligations and entitlements, land rights, child custody and family property disputes, social security and welfare rights. ",
"This degree opens up a rewarding career in many areas of business, finance or government. Graduate positions may include: Business analyst, Economic forecaster, Graduate economist, Management consultant, Policy advisor, Statistical analyst, Superannuation advisor. Related careers in accounting, finance, human resource management, information systems, marketing and taxation. ",
"",
"Anatomist, Conservation Scientist, Field Officer, Product Analyst, Science Communicator ",
"IS/IT consultants, IT infrastructure developers, Network developers, Systems analysts, Technical managers, IS/IT architects ",
"",
"Anthropologist, Community Development Worker, Climate Analyst, Policy Specialist, Entrepreneur, Environmental Consultant, Science Communicator ",
"There is strong demand for graduates in actuarial studies, especially in the financial services, insurance and superannuation industry. As a graduate, you can work as an actuarial analyst, consultant, asset management trainee, credit analyst, forecasting analyst, insurance analyst, risk assessment officer, statistical research analyst, superannuation advisor or wealth management analyst. ",
"",
"The program has been designed for students whose passion is science, but who also recognise that awareness of contemporary business practices can be vital in the modern workplace. ",
"As a graduate, you will be equipped with specialist technical skills which are the building blocks for a career in business, as well as developed analytical skills. You will be qualified to pursue a range of careers across local and international organisations, government and not-for-profit organisations and work as an accountant, economist, strategy consultant, business manager, marketing specialist, information systems consultant, taxation advisor, investment banker, or policy advisor. ",
"",
"For those wishing to use their degree in psychology as a general training for future employment, the skills acquired during the degree in psychological science are extremely valuable to a wide variety of careers. Psychologists work in a range of organisations within both the public and private sector. These include clinical and health settings such as clinics and hospitals, a diverse collection of commercial and non-profit organisations, and forensic settings such as prisons and law courts. Employers range from the army to schools, from the Roads and Maritime Service to the Department of Health. For those wishing to practice as a specialist professional psychologist, typical areas of work include clinical, organisational, forensic, counselling and educational psychology. Psychologists are employed across several industries including health care and social assistance, public administration and safety, education and training, and administrative and support services. This mix of industries is highly favourable for employment growth prospects. ",
"As a graduate, you can find employment in diverse professions within the commerce industry depending on your choice of major in the commerce degree. You can work in government agencies including foreign affairs, investment banks and other financial institutions with international links as well as nongovernment organisations. ",
"",
"Psychologist, Clinical Psychologist, Forensic Psychologist, Organisational Psychologist, Community Development Worker, Medical Scientist, Management Consultant ",
"This degree opens up a rewarding career in many areas of business, finance or government. Graduate positions may include: Business analyst, Economic forecaster, Graduate economist, Management consultant, Policy advisor, Statistical analyst, Superannuation advisor. Related careers in accounting, finance, human resource management, information systems, marketing and taxation. ",
"",
"A professional qualification in psychology leads to careers in clinical, organisational and forensic settings as well as teaching and research. The main employer of trained psychologists is the government sector where psychologists work in areas ranging from health, education and community services through to police, corrective services, industrial relations and road and traffic authorities. Other employers are tertiary institutions, management and personnel consultants, market research organisations and banks. Many psychologists also work in private employment as clinical, educational or industrial consultants. ",
"There is strong demand for graduates in actuarial studies, especially in the financial services, insurance and superannuation industry. As a graduate, you can work as an actuarial analyst, consultant, asset management trainee, credit analyst, forecasting analyst, insurance analyst, risk assessment officer, statistical research analyst, superannuation advisor or wealth management analyst. ",
"",
"As a graduate, you will be equipped with specialist technical skills which are the building blocks for a career in business, as well as developed analytical skills. You will be qualified to pursue a range of careers across local and international organisations, government and not-for-profit organisations and work as an accountant, economist, strategy consultant, business manager, marketing specialist, information systems consultant, taxation advisor, investment banker, or policy advisor. ",
"",
"As a graduate, you can find employment in diverse professions within the commerce industry depending on your choice of major in the commerce degree. You can work in government agencies including foreign affairs, investment banks and other financial institutions with international links as well as nongovernment organisations. ",
"Graduates find employment in the aerospace design and manufacturing industry including aerospace companies, airlines, defence forces and government regulators. ",
"This degree opens up a rewarding career in many areas of business, finance or government. Graduate positions may include: Business analyst, Economic forecaster, Graduate economist, Management consultant, Policy advisor, Statistical analyst, Superannuation advisor. Related careers in accounting, finance, human resource management, information systems, marketing and taxation. ",
"Graduates may find employment with companies involved in product design and development, manufacturing companies of all types, service providers such as banks or forwarding agencies, distribution companies, warehousing and logistics, consulting companies undertaking a variety of tasks such as the economic analysis of planning and implementation of strategies and technologies. ",
"There is strong demand for graduates in actuarial studies, especially in the financial services, insurance and superannuation industry. As a graduate, you can work as an actuarial analyst, consultant, asset management trainee, credit analyst, forecasting analyst, insurance analyst, risk assessment officer, statistical research analyst, superannuation advisor or wealth management analyst. ",
"Mechanical engineers are involved in a wide variety of essential industries. Graduates may find employment with major companies operating in diverse manufacturing industries such as car building; machine design and construction companies; consulting companies which provide specialised services such as stress analysis, noise and vibration analysis and building services design and power and water supply companies. ",
"As a graduate, you will be equipped with specialist technical skills which are the building blocks for a career in business, as well as developed analytical skills. You will be qualified to pursue a range of careers across local and international organisations, government and not-for-profit organisations and work as an accountant, economist, strategy consultant, business manager, marketing specialist, information systems consultant, taxation advisor, investment banker, or policy advisor. ",
"Mechatronic engineers can find employment throughout the range of fields which are normally covered by mechanical, electrical and computer engineering. You may find employment with companies which design and manufacture consumer machines; companies which design, manufacture and install specialised industrial machines; companies whose primary interests relate to mechanical, electrical or computer engineering; and with consulting engineers dealing with complex project management across a range of engineering disciplines. ",
"As a graduate, you can find employment in diverse professions within the commerce industry depending on your choice of major in the commerce degree. You can work in government agencies including foreign affairs, investment banks and other financial institutions with international links as well as nongovernment organisations. ",
"This degree opens up a rewarding career in many areas of business, finance or government. Graduate positions may include: Business analyst, Economic forecaster, Graduate economist, Management consultant, Policy advisor, Statistical analyst, Superannuation advisor. Related careers in accounting, finance, human resource management, information systems, marketing and taxation. ",
"Mine Manager, Mine Planner and Designer, Management Consultant, Operations Manager, Technical Services Manager, Researcher, Investment Analyst and Advisor, General Manager, Chief Executive, Mine Inspector, Government Inspector, Consultant, Service Provider, Production Superintendent, Minerals Processing Engineer. ",
"There is strong demand for graduates in actuarial studies, especially in the financial services, insurance and superannuation industry. As a graduate, you can work as an actuarial analyst, consultant, asset management trainee, credit analyst, forecasting analyst, insurance analyst, risk assessment officer, statistical research analyst, superannuation advisor or wealth management analyst. ",
"As a graduate, you will be equipped with specialist technical skills which are the building blocks for a career in business, as well as developed analytical skills. You will be qualified to pursue a range of careers across local and international organisations, government and not-for-profit organisations and work as an accountant, economist, strategy consultant, business manager, marketing specialist, information systems consultant, taxation advisor, investment banker, or policy advisor. ",
"Petroleum engineers have a number of career choices. As a graduate, you can work in oil/gas companies or oil service companies in Australia and internationally. Work will be a combination of outdoors and office work if you choose this type of career. Working with computer-generated modelling of reservoirs is another type of career. ",
"As a graduate, you can find employment in diverse professions within the commerce industry depending on your choice of major in the commerce degree. You can work in government agencies including foreign affairs, investment banks and other financial institutions with international links as well as nongovernment organisations. ",
"Graduates may work globally in all aspects of photovoltaic and renewable energy engineering including: manufacturing, quality control and reliability, computer-aided design of devices and systems, research and education, system design and analysis, balance of system areas, fault diagnosis and modelling, marketing, policy formation and planning and programs in developing countries. ",
"This degree opens up a rewarding career in many areas of business, finance or government. Graduate positions may include: Business analyst, Economic forecaster, Graduate economist, Management consultant, Policy advisor, Statistical analyst, Superannuation advisor. Related careers in accounting, finance, human resource management, information systems, marketing and taxation. ",
"Graduates may work globally in all aspects of photovoltaic and renewable energy engineering including: manufacturing, quality control and reliability, computer-aided design of devices and systems, research and education, system design and analysis, balance of system areas, fault diagnosis and modelling, marketing, policy formation and planning and programs in developing countries. ",
"There is strong demand for graduates in actuarial studies, especially in the financial services, insurance and superannuation industry. As a graduate, you can work as an actuarial analyst, consultant, asset management trainee, credit analyst, forecasting analyst, insurance analyst, risk assessment officer, statistical research analyst, superannuation advisor or wealth management analyst. ",
"As a graduate, you will be equipped with specialist technical skills which are the building blocks for a career in business, as well as developed analytical skills. You will be qualified to pursue a range of careers across local and international organisations, government and not-for-profit organisations and work as an accountant, economist, strategy consultant, business manager, marketing specialist, information systems consultant, taxation advisor, investment banker, or policy advisor. ",
"As a graduate, you can find employment in diverse professions within the commerce industry depending on your choice of major in the commerce degree. You can work in government agencies including foreign affairs, investment banks and other financial institutions with international links as well as nongovernment organisations. ",
"This degree opens up a rewarding career in many areas of business, finance or government. Graduate positions may include: Business analyst, Economic forecaster, Graduate economist, Management consultant, Policy advisor, Statistical analyst, Superannuation advisor. Related careers in accounting, finance, human resource management, information systems, marketing and taxation. ",]
dd = {}

for i in range(len(list1)):
    dd[list1[i]] = listvalue[i]
# print(dd)
