from scrapy import cmdline
# cmdline.execute("scrapy crawl bristolMasters".split())
# cmdline.execute("scrapy crawl strathMasters".split())
# cmdline.execute("scrapy crawl manchesterMasters".split())
# cmdline.execute("scrapy crawl durhamMasters".split())
# cmdline.execute("scrapy crawl kingsMasters".split())
# cmdline.execute("scrapy crawl manchesterResearchMasters".split())
# cmdline.execute("scrapy crawl strathResearchMasters".split())
# cmdline.execute("scrapy crawl astonMasters".split())
# cmdline.execute("scrapy crawl salfordBen".split())
# cmdline.execute("scrapy crawl salfordMastersTaught".split())
cmdline.execute("scrapy crawl salfordMastersResearch".split())
# cmdline.execute("scrapy crawl bathspaBen".split())
# cmdline.execute("scrapy crawl hertsBen".split())
# cmdline.execute("scrapy crawl uclanBen".split())
# cmdline.execute("scrapy crawl cardiffmetBen".split())